services:
  - type: web
    name: hagiang-backend
    runtime: docker
    rootDir: backend
    plan: free
    healthCheckPath: /api/experiences
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: ha-giang-local-experience
